---
# The "Stale" workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
# However, this implementation is configured to only work with PRs, ignoring issues.
# For more information, see: https://github.com/actions/stale

name: Stale

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 6 * * *' # Runs at 6am UTC every day
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  stale:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # List of permissions granted to the GITHUB_TOKEN
    permissions:
      issues: write
      pull-requests: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/stale@v5
        with:
          debug-only: false # Runs the stale workflow as dry-run
          repo-token: ${{ secrets.GITHUB_TOKEN }} # PAT for GitHub authentication
          operations-per-run: 500 # Limits the number of operations made with GitHub API to avoid reaching rate limit
          exempt-pr-labels: 'dependencies' # PRs with these labels are not marked as stale
          delete-branch: true # Automatically delete branches when closing pull requests
          days-before-pr-stale: 45 # Idle number of days before marking PRs as stale
          days-before-pr-close: 21 # Idle number of days before closing the stale PRs
          stale-pr-message: > # Message that will be added as a comment to PRs when they are labeled as stale
            This pull request has been automatically marked as stale because it had not had any recent activity.
            It will be closed and corresponding branch deleted if no further activity occurs during the next 3 weeks.
          close-pr-message: > # Message that will be added as a comment to PRs when they are closed
            This pull request has been automatically closed and its branch has been deleted because of inactivity.
            You can re-open the pull request and restore the branch if needed.
